services:
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
    volumes:
      - .:/app
    command: gunicorn --bind 0.0.0.0:5001 app:app
    restart: unless-stopped  # Ensures the container restarts on reboot
